###############################################
@gen_challenge = (user) ->
	challenge =
		num_reviews: 2

	res = store_document_unprotected Challenges, challenge, user, true
	msg = "Challenge (" + challenge._id + ") generated by: " + get_user_mail user
	log_event msg, event_logic, event_info

	return res

###############################################
@bake_challenge = (user,title,content,link,type) ->
	challenge =
		num_reviews: 2
		title: title
		content: content
		link: link
		type: type

	res = store_document_unprotected Challenges, challenge, user, true
	msg = "Challenge (" + challenge._id + ") generated by: " + get_user_mail user
	log_event msg, event_logic, event_info

	return res

###############################################
@finish_challenge = (challenge, user) ->
	modify_field_unprotected Challenges, challenge._id, "published", true
	modify_field_unprotected Challenges, challenge._id, "visible_to", "anonymous"

	#TODO: inform last round participants

	msg = "Challenge (" + challenge._id + ") published by: " + get_user_mail user
	log_event msg, event_logic, event_info

	return challenge._id