###############################################
@gen_question = (user) ->
	question =
		owner_id: user._id

	res = store_document_unprotected Questions, question
	msg = "Question (" + question._id + ") generated by: " + get_user_mail user
	log_event msg, event_logic, event_info

	return res


###############################################
@finish_question = (question, user) ->
	modify_field_unprotected Questions, question._id, "published", true
	modify_field_unprotected Questions, question._id, "visible_to", "anonymous"

	#TODO: inform last round participants

	msg = "Question (" + question._id + ") published by: " + get_user_mail user
	log_event msg, event_logic, event_info

	return question._id
