###############################################
@gen_recommendation = (user, recipient_id) ->
	recommendation =
		recipient_id: recipient_id

	res = store_document_unprotected Recommendations, recommendation, user, true
	msg = "Recommendation (" + res._id + ") generated by: " + get_user_mail user
	log_event msg, event_logic, event_info

	return res


###############################################
@finish_recommendation = (recommendation, user) ->
	modify_field_unprotected Recommendations, recommendation._id, "published", true
	modify_field_unprotected Recommendations, recommendation._id, "visible_to", "anonymous"

	msg = "Challenge (" + challenge._id + ") published by: " + get_user_mail user
	log_event msg, event_logic, event_info

	return challenge._id